services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_restapi
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-data:/var/log/mysql

volumes:
  db-data:
